---
- name: Install required packages
  apt:
    name:
      - openjdk-8-jdk
      - python3
      - python3-pip
      - vim
      - ufw
      - tmux
      - git
      - wget
      - curl
      - build-essential
      - make
      - xz-utils
      - file
      - liblzma-dev
      - patch
      - zlib1g-dev
      - g++
      - gnupg
      - gcc
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - unzip
      - net-tools
      - libcurl4
      - libltdl7
      - libncurses5
      - libncursesw5
      - libstdc++6
      - ntp
      - ntpdate
      
    state: present
    update_cache: yes
