---
db_hostname: "{{ hostvars[groups['db_servers_nodes'][0]]['inventory_hostname'] }}"
scm_hostname: "{{ hostvars[groups['masters_nodes'][0]]['inventory_hostname'] }}"

cluster_name: ishaq_merzoug_cluster_1

needed_service:
  - HDFS
  - YARN
  - ZOOKEEPER
  - HIVE
  - SPARK_ON_YARN
  - KAFKA
  - HUE
