- name: Add services
  hosts: cloudera_manager_server
  vars_files:
    - ./vars/all.yml
    - ./vars/cdp_clusters.yml

  roles:
    - cloudera_generate_api_uri

  tasks:
    - name: Add services
      include_role:
        name: cloudera_add_services
      vars:
        service_name: "{{ item }}"
        service_type: "{{ item }}"
      loop: "{{ needed_service }}"

#    - include_role: 
#        name: cloudera_add_services_roles
