---
- name: Create a cloudera cluster with needed services
  hosts: cloudera_manager_server
  vars_files:
    - ./vars/all.yml
    - ./vars/cdp_clusters.yml
    
  roles:
    - cloudera_create_cluster